"""Fine-grained BigBird paragraphs: original + zh + paragraph summary.

Fidelity note: English text follows arXiv:2007.14062 closely (minor
normalization for PDF ligatures / line breaks). Tables and figure captions
are paraphrased into readable prose where OCR layout breaks sentences.
"""

# Each para: en, zh, summary, terms (optional), figure (optional: "pattern"|"block")

SECTIONS = [
    {
        "id": "abstract",
        "title": "Abstract 摘要",
        "paras": [
            {
                "en": "Transformers-based models, such as BERT, have been one of the most successful deep learning models for NLP. Unfortunately, one of their core limitations is the quadratic dependency (mainly in terms of memory) on the sequence length due to their full attention mechanism.",
                "zh": "以 BERT 为代表的 Transformer 模型，已成为 NLP 中最成功的深度学习模型之一。但它们有一个核心局限：由于采用全注意力机制，对序列长度存在二次依赖（主要体现在内存上）。",
                "summary": "开场点题：Transformer 很成功，但全注意力吃长度——内存随 n² 涨。",
                "terms": ["full attention", "quadratic dependency"],
            },
            {
                "en": "To remedy this, we propose, BIGBIRD, a sparse attention mechanism that reduces this quadratic dependency to linear. We show that BIGBIRD is a universal approximator of sequence functions and is Turing complete, thereby preserving these properties of the quadratic, full attention model.",
                "zh": "为此，我们提出 BIGBIRD：一种把上述二次依赖降为线性的稀疏注意力机制。我们证明 BIGBIRD 是序列函数的万能近似器，并且是图灵完备的，从而保留了二次全注意力模型的这些性质。",
                "summary": "方法 + 理论双承诺：线性稀疏，且表达力不丢（万能近似 + 图灵完备）。",
                "terms": ["sparse attention", "universal approximator", "Turing complete"],
            },
            {
                "en": "Along the way, our theoretical analysis reveals some of the benefits of having O(1) global tokens (such as CLS), that attend to the entire sequence as part of the sparse attention mechanism.",
                "zh": "在此过程中，理论分析揭示了引入 O(1) 个全局 token（例如 CLS）的部分好处：它们作为稀疏注意力的一部分，会对整个序列做注意力。",
                "summary": "全局 token 不是拍脑袋：理论分析说明「常数个全局位」有用。",
                "terms": ["global tokens", "CLS"],
            },
            {
                "en": "The proposed sparse attention can handle sequences of length up to 8x of what was previously possible using similar hardware. As a consequence of the capability to handle longer context, BIGBIRD drastically improves performance on various NLP tasks such as question answering and summarization. We also propose novel applications to genomics data.",
                "zh": "在相近硬件上，所提稀疏注意力可处理的序列长度可达以往的约 8 倍。由于能吃更长上下文，BIGBIRD 在问答、摘要等多种 NLP 任务上大幅提升表现。我们还提出面向基因组数据的新应用。",
                "summary": "经验卖点：约 8× 长度；QA/摘要大涨；还能做基因组。",
                "terms": [],
            },
        ],
    },
    {
        "id": "intro",
        "title": "1 Introduction 引言",
        "paras": [
            {
                "en": "Models based on Transformers, such as BERT, are wildly successful for a wide variety of Natural Language Processing (NLP) tasks and consequently are mainstay of modern NLP research. Their versatility and robustness are the primary drivers behind the wide-scale adoption of Transformers.",
                "zh": "基于 Transformer 的模型（如 BERT）在各类 NLP 任务上极为成功，因而成为现代 NLP 研究的中流砥柱。其通用性与稳健性，是 Transformer 被广泛采用的主要动力。",
                "summary": "先立功：Transformer/BERT 已经是默认底座。",
                "terms": ["Transformer", "BERT"],
            },
            {
                "en": "The model is easily adapted for a diverse range of sequence based tasks – as a seq2seq model for translation, summarization, generation, etc. or as a standalone encoders for sentiment analysis, POS tagging, machine reading comprehension, etc. – and it is known to vastly outperform previous sequence models like LSTM.",
                "zh": "该模型很容易适配多样的序列任务——既可作翻译、摘要、生成等 seq2seq 模型，也可作情感分析、词性标注、机器阅读理解等独立编码器——并且远超 LSTM 等以往序列模型。",
                "summary": "适用面：生成与编码两边都能打，整体强于 LSTM。",
                "terms": ["seq2seq", "LSTM"],
            },
            {
                "en": "The key innovation in Transformers is the introduction of a self-attention mechanism, which can be evaluated in parallel for each token of the input sequence, eliminating the sequential dependency in recurrent neural networks, like LSTM. This parallelism enables Transformers to leverage the full power of modern SIMD hardware accelerators like GPUs/TPUs, thereby facilitating training of NLP models on datasets of unprecedented size.",
                "zh": "Transformer 的关键创新是自注意力：可对输入序列的每个 token 并行计算，消除了 LSTM 这类 RNN 的串行依赖。这种并行性使模型能吃满 GPU/TPU 等 SIMD 加速器，从而在前所未有规模的数据上训练 NLP 模型。",
                "summary": "自注意力 → 并行 → 吃满硬件 → 超大规模预训练成为可能。",
                "terms": ["self-attention", "SIMD"],
            },
            {
                "en": "This ability to train on large scale data has led to surfacing of models like BERT and T5, which pretrain transformers on large general purpose corpora and transfer the knowledge to down-stream task. The pretraining has led to significant improvement in low data regime downstream tasks as well as tasks with sufficient data and thus have been a major force behind the ubiquity of transformers in contemporary NLP.",
                "zh": "大规模训练能力催生了 BERT、T5 等模型：在通用大语料上预训练 Transformer，再把知识迁移到下游任务。预训练在低数据与充足数据下游任务上都带来显著提升，因此成为当代 NLP 中 Transformer 无处不在的重要推手。",
                "summary": "预训练范式解释了「为什么人人都用 Transformer」。",
                "terms": ["pretraining", "T5"],
            },
            {
                "en": "The self-attention mechanism overcomes constraints of RNNs (namely the sequential nature of RNN) by allowing each token in the input sequence to attend independently to every other token in the sequence. This design choice has several interesting repercussions. In particular, the full self-attention have computational and memory requirement that is quadratic in the sequence length.",
                "zh": "自注意力通过让每个 token 独立地关注序列中每一个其他 token，克服了 RNN 的串行约束。这一设计带来若干重要后果：尤其是，全自注意力的计算与内存需求对序列长度是二次的。",
                "summary": "全连接的代价：每个 token 看所有人 → O(n²)。",
                "terms": ["full self-attention"],
            },
            {
                "en": "We note that while the corpus can be large, the sequence length, which provides the context in many applications is very limited. Using commonly available current hardware and model sizes, this requirement translates to roughly being able to handle input sequences of length 512 tokens. This reduces its direct applicability to tasks that require larger context, like QA, document classification, etc.",
                "zh": "需要注意：语料可以很大，但许多应用里提供上下文的序列长度却非常有限。在常见硬件与模型规模下，这一要求大约对应只能处理长度约 512 的输入。这削弱了它在需要更大上下文的任务（如问答、文档分类等）上的直接可用性。",
                "summary": "落地数字：常见设定 ≈ 512；QA/长文档直接吃亏。",
                "terms": ["sequence length 512"],
            },
            {
                "en": "However, while we know that self-attention and Transformers are useful, our theoretical understanding is rudimentary. What aspects of the self-attention model are necessary for its performance? What can we say about the expressivity of Transformers and similar models? Apriori, it was not even clear from the design if the proposed self-attention mechanism was as effective as RNNs. For example, the self-attention does not even obey sequence order as it is permutation equivariant.",
                "zh": "然而，尽管我们知道自注意力与 Transformer 有用，理论理解仍很粗浅。自注意力模型的哪些方面对其性能必要？关于 Transformer 及类似模型的表达力，我们能说什么？先验地，甚至不清楚所提自注意力是否能与 RNN 一样有效——例如，自注意力是置换等变的，本身并不遵守序列顺序。",
                "summary": "理论缺口：哪些结构必要？表达力如何？连「是否真比得上 RNN」都曾不清楚。",
                "terms": ["permutation equivariant", "expressivity"],
            },
            {
                "en": "This concern has been partially resolved, as Yun et al. showed that transformers are expressive enough to capture all continuous sequence to sequence functions with a compact domain. Meanwhile, Pérez et al. showed that the full transformer is Turing Complete (i.e. can simulate a full Turing machine). Two natural questions arise: Can we achieve the empirical benefits of a fully quadratic self-attention scheme using fewer inner-products? Do these sparse attention mechanisms preserve the expressivity and flexibility of the original network?",
                "zh": "这一担忧已部分解除：Yun 等证明 Transformer 足以刻画紧集上所有连续的序列到序列函数；Pérez 等证明完整 Transformer 是图灵完备的（可模拟完整图灵机）。于是自然出现两个问题：能否用更少的内积，仍获得全二次自注意力的经验收益？这些稀疏注意力机制能否保留原网络的表达力与灵活性？",
                "summary": "全文两个核心问题：更少内积是否够用？稀疏后表达力还在吗？",
                "terms": ["universal approximator", "Turing complete"],
            },
            {
                "en": "In this paper, we address both the above questions and produce a sparse attention mechanism that improves performance on a multitude of tasks that require long contexts. We systematically develop BIGBIRD, an attention mechanism whose complexity is linear in the number of tokens (Sec. 2).",
                "zh": "本文同时回应上述两个问题，并提出一种在大量需长上下文任务上提升表现的稀疏注意力机制。我们系统发展 BIGBIRD：一种复杂度对 token 数线性的注意力机制（第 2 节）。",
                "summary": "本文贡献预告：回答理论问题 + 给出线性复杂度的 BIGBIRD。",
                "terms": ["BIGBIRD"],
            },
            {
                "en": "We take inspiration from graph sparsification methods and understand where the proof for expressiveness of Transformers breaks down when full-attention is relaxed to form the proposed attention pattern. This understanding helped us develop BIGBIRD, which is theoretically as expressive and also empirically useful.",
                "zh": "我们从图稀疏化方法汲取灵感，并弄清：当把全注意力放松为所提注意力图案时，Transformer 表达力证明在何处会失效。这种理解帮助我们设计出既在理论上同样有表达力、又在经验上有用的 BIGBIRD。",
                "summary": "设计方法：看证明在哪断 → 用图结构把断点补回来。",
                "terms": ["graph sparsification"],
            },
            {
                "en": "In particular, our BIGBIRD consists of three main parts: A set of g global tokens attending on all parts of the sequence. All tokens attending to a set of w local neighboring tokens. All tokens attending to a set of r random tokens.",
                "zh": "具体而言，BIGBIRD 由三部分组成：（1）一组 g 个全局 token，关注序列的所有部分；（2）所有 token 关注一组 w 个局部邻近 token；（3）所有 token 关注一组 r 个随机 token。",
                "summary": "三件套务必背熟：全局 g + 窗口 w + 随机 r。",
                "terms": ["global tokens", "window attention", "random attention"],
            },
            {
                "en": "This leads to a high performing attention mechanism scaling to much longer sequence lengths (8x). To summarize, our main contributions are: (1) BIGBIRD satisfies all the known theoretical properties of full transformer (Sec. 3). In particular, we show that adding extra tokens allows one to express all continuous sequence to sequence functions with only O(n)-inner products. Furthermore, we show that under standard assumptions regarding precision, BIGBIRD is Turing complete. (2) Empirically, we show that the extended context modelled by BIGBIRD benefits a variety of NLP tasks. We achieve state of the art results for question answering and document summarization on a number of different datasets. (3) Lastly, we introduce a novel application of attention based models where long contexts are beneficial: extracting contextual representations of genomics sequences like DNA.",
                "zh": "由此得到可扩展到更长序列（约 8×）的高性能注意力。贡献总结：（1）理论——BIGBIRD 满足全 Transformer 已知理论性质；添加额外 token 后仅用 O(n) 内积即可表达所有连续 seq2seq 函数；在精度等标准假设下图灵完备。（2）经验——更长上下文使多种 NLP 任务受益，在若干数据集的问答与文档摘要上达到 SOTA。（3）新应用——用注意力模型为 DNA 等基因组序列提取上下文表示。",
                "summary": "三条贡献：理论不丢、NLP 长文 SOTA、基因组新场景。",
                "terms": ["O(n) inner products"],
            },
        ],
    },
    {
        "id": "related",
        "title": "1.1 Related Work 相关工作",
        "paras": [
            {
                "en": "There have been a number of interesting attempts aimed at alleviating the quadratic dependency of Transformers, which can be broadly categorized into two directions. First line of work embraces the length limitation and develops methods around it. Simplest methods in this category just employ sliding window, but in general most work fits in the following general paradigm: using some other mechanism select a smaller subset of relevant contexts to feed in the transformer and optionally iterate, i.e. call transformer block multiple times with different contexts each time.",
                "zh": "已有不少工作试图缓解 Transformer 的二次依赖，大致可分为两个方向。第一类接受长度限制，并在此基础上发展方法：最简单的是滑动窗口；更一般的范式是：用别的机制先选出更小的相关上下文子集再送入 Transformer，并可选择迭代——即多次用不同上下文调用 Transformer 块。",
                "summary": "路线一：不硬改注意力，先裁上下文再喂进标准 Transformer。",
                "terms": ["sliding window"],
            },
            {
                "en": "Most prominently, SpanBERT, ORQA, REALM, RAG have achieved strong performance for different tasks. However, it is worth noting that these methods often require significant engineering efforts (like back prop through large scale nearest neighbor search) and are hard to train.",
                "zh": "其中 SpanBERT、ORQA、REALM、RAG 等在不同任务上表现强劲。但需注意：这些方法往往需要大量工程（例如对大规模近邻检索做反传），训练也很难。",
                "summary": "检索增强很强，但工程重、难训——不是本文主线。",
                "terms": [],
            },
            {
                "en": "Second line of work questions if full attention is essential and have tried to come up with approaches that do not require full attention, thereby reducing the memory and computation requirements. Prominently, Dai et al., Sukhbaatar et al., Rae et al. have proposed auto-regressive models that work well for left-to-right language modeling but suffer in tasks which require bidirectional context. Child et al. proposed Sparse Transformer; Ye et al. proposed binary partitions of the data whereas Qiu et al. reduced complexity by using block sparsity.",
                "zh": "第二类质疑全注意力是否必要，并尝试不需要全注意力的方法以降低内存与计算。代表性工作中，Dai / Sukhbaatar / Rae 等提出的自回归模型对从左到右语言模型效果好，但在需要双向上下文的任务上吃亏。Child 等提出 Sparse Transformer；Ye 等用数据二分；Qiu 等用块稀疏降复杂度。",
                "summary": "路线二：改注意力本身；BigBird 站在这条线上。",
                "terms": ["Sparse Transformer", "block sparsity"],
            },
            {
                "en": "Recently, Longformer introduced a localized sliding window based mask with few global mask to reduce computation and extended BERT to longer sequence based tasks. Finally, our work is closely related to and built on the work of Extended Transformers Construction (ETC). This work was designed to encode structure in text for transformers. The idea of global tokens was used extensively by them to achieve their goals. Our theoretical work can be seen as providing a justification for the success of these models as well.",
                "zh": "近期，Longformer 引入基于局部滑动窗口掩码并配合少量全局掩码以降低计算，并把 BERT 扩展到更长序列任务。我们的工作与 Extended Transformers Construction（ETC）密切相关并建立其上：ETC 旨在为 Transformer 编码文本结构，并大量使用全局 token。我们的理论工作也可视为为这些模型的成功提供了一种辩护。",
                "summary": "谱系定位：Longformer（窗+全局）与 ETC（全局 token）是近亲；BigBird 补理论与随机边。",
                "terms": ["Longformer", "ETC"],
            },
            {
                "en": "It is important to note that most of the aforementioned methods are heuristic based and empirically are not as versatile and robust as the original transformer, i.e. the same architecture do not attain SoTA on multiple standard benchmarks. (There is one exception of Longformer which we include in all our comparisons.) Moreover, these approximations do not come with theoretical guarantees.",
                "zh": "需要强调：上述多数方法偏启发式，经验上也不如原始 Transformer 通用稳健——同一架构往往无法在多个标准基准上同时达到 SOTA（Longformer 是例外，我们在所有比较中都纳入）。此外，这些近似通常没有理论保证。",
                "summary": "批评前人：缺理论、难通吃多基准；本文要对齐这两点。",
                "terms": [],
            },
        ],
    },
    {
        "id": "arch",
        "title": "2 BIGBIRD Architecture 架构（核心）",
        "paras": [
            {
                "en": "In this section, we describe the BIGBIRD model using the generalised attention mechanism that is used in each layer of transformer operating on an input sequence X = (x₁, …, xₙ) ∈ Rⁿˣᵈ.",
                "zh": "本节用「广义注意力机制」描述 BIGBIRD：它用于 Transformer 每一层，作用在输入序列 X = (x₁, …, xₙ) ∈ Rⁿˣᵈ 上。",
                "summary": "设定：输入是 n 个 d 维向量。",
                "terms": [],
            },
            {
                "en": "The generalized attention mechanism is described by a directed graph D whose vertex set is [n] = {1, …, n}. The set of arcs (directed edges) represent the set of inner products that the attention mechanism will consider. Let N(i) denote the out-neighbors set of node i in D, then the i-th output vector of the generalized attention mechanism is defined as ATTN_D(X)_i = x_i + Σ_h σ( Q_h(x_i) K_h(X_{N(i)})ᵀ ) · V_h(X_{N(i)}).",
                "zh": "广义注意力由有向图 D 描述，顶点集为 [n]={1,…,n}。弧（有向边）表示注意力会考虑的内积集合。令 N(i) 为节点 i 在 D 中的出邻域，则第 i 个输出为：ATTN_D(X)_i = x_i + Σ_h σ( Q_h(x_i) K_h(X_{N(i)})ᵀ ) · V_h(X_{N(i)})。",
                "summary": "关键改写：不是对全体做 QK，只对图上邻居 N(i) 做。",
                "terms": ["generalized attention", "out-neighbors N(i)"],
            },
            {
                "en": "where Q_h, K_h : Rᵈ → Rᵐ are query and key functions respectively, V_h : Rᵈ → Rᵈ is a value function, σ is a scoring function (e.g. softmax or hardmax) and H denotes the number of heads. Also note X_{N(i)} corresponds to the matrix formed by only stacking {x_j : j ∈ N(i)} and not all the inputs. If D is the complete digraph, we recover the full quadratic attention mechanism of Vaswani et al.",
                "zh": "其中 Q_h、K_h 是 query/key 函数，V_h 是 value 函数，σ 是打分函数（如 softmax 或 hardmax），H 为头数。X_{N(i)} 只由邻居 {x_j : j∈N(i)} 堆叠而成，而非全部输入。若 D 是完全有向图，则退回 Vaswani 等的全二次注意力。",
                "summary": "完全图 = 标准 Transformer；稀疏图 = 少算内积。",
                "terms": ["softmax", "complete digraph"],
            },
            {
                "en": "To simplify our exposition, we will operate on the adjacency matrix A of the graph D even though the underlying graph maybe sparse. To elaborate, A ∈ [0,1]^{n×n} with A(i,j)=1 if query i attends to key j and is zero otherwise. For example, when A is the ones matrix (as in BERT), it leads to quadratic complexity, since all tokens attend on every other token. This view of self-attention as a fully connected graph allows us to exploit existing graph theory to help reduce its complexity.",
                "zh": "为叙述简便，我们在图 D 的邻接矩阵 A 上讨论（即便图稀疏）。A ∈ [0,1]^{n×n}，A(i,j)=1 表示 query i 关注 key j，否则为 0。例如 BERT 中 A 全为 1，导致二次复杂度，因为所有 token 互相关注。把自注意力看成全连接图，便可借助图论来降低复杂度。",
                "summary": "操作对象变成掩码矩阵 A：1=算注意力，0=不算。",
                "terms": ["adjacency matrix"],
            },
            {
                "en": "The problem of reducing the quadratic complexity of self-attention can now be seen as a graph sparsification problem. It is well-known that random graphs are expanders and can approximate complete graphs in a number of different contexts including in their spectral properties. We believe sparse random graph for attention mechanism should have two desiderata: small average path length between nodes and a notion of locality, each of which we discuss below.",
                "zh": "于是，降低自注意力二次复杂度可视为图稀疏化问题。众所周知，随机图是扩展图，能在包括谱性质在内的多种意义下近似完全图。我们认为，用于注意力的稀疏随机图应具备两点：节点间平均路径短，以及某种局部性——下文分别讨论。",
                "summary": "设计目标二象性：路径要短（信息传得快）+ 要有局部性（语言邻近重要）。",
                "terms": ["graph sparsification", "expander", "average path length", "locality"],
            },
            {
                "en": "Let us consider the simplest random graph construction, known as Erdős-Rényi model, where each edge is independently chosen with a fixed probability. In such a random graph with just Θ̃(n) edges, the shortest path between any two nodes is logarithmic in the number of nodes. As a consequence, such a random graph approximates the complete graph spectrally and its second eigenvalue (of the adjacency matrix) is quite far from the first eigenvalue. This property leads to a rapid mixing time for random walks in the graph, which informally suggests that information can flow fast between any pair of nodes. Thus, we propose a sparse attention where each query attends over r random number of keys i.e. A(i,·)=1 for r randomly chosen keys (see Fig. 1a).",
                "zh": "考虑最简单的随机图：Erdős-Rényi 模型，每条边以固定概率独立出现。在仅有 Θ̃(n) 条边的此类图中，任意两点最短路径对节点数是对数级的。因此它在谱上近似完全图，邻接矩阵第二特征值与第一特征值相距较远，随机游走混合快——非正式地说，信息能在任意节点对之间快速流动。于是我们提出：每个 query 关注 r 个随机 key，即对随机选出的 r 个位置令 A(i,·)=1（见图 1a）。",
                "summary": "积木① 随机注意力：每行约 r 个随机 1，换「短路径 / 快混合」。",
                "terms": ["Erdős-Rényi", "random attention", "mixing time"],
                "figure": "pattern",
            },
            {
                "en": "The second viewpoint which inspired the creation of BIGBIRD is that most contexts within NLP and computational biology have data which displays a great deal of locality of reference. In this phenomenon, a great deal of information about a token can be derived from its neighboring tokens. Most pertinently, Clark et al. investigated self-attention models in NLP tasks and concluded that neighboring inner-products are extremely important.",
                "zh": "启发 BIGBIRD 的第二观点是：NLP 与计算生物学中的多数上下文数据具有很强的引用局部性——关于一个 token 的大量信息可从其邻近 token 得到。尤其 Clark 等在 NLP 任务上研究自注意力后得出：邻近位置的内积极为重要。",
                "summary": "积木② 的动机：语言/生物序列高度「看邻居」。",
                "terms": ["locality of reference"],
            },
            {
                "en": "The concept of locality, proximity of tokens in linguistic structure, also forms the basis of various linguistic theories such as transformational-generative grammar. In the terminology of graph theory, clustering coefficient is a measure of locality of connectivity, and is high when the graph contains many cliques or near-cliques. Simple Erdős-Rényi random graphs do not have a high clustering coefficient, but a class of random graphs, known as small world graphs, exhibit high clustering coefficient.",
                "zh": "局部性（语言结构中 token 的邻近）也是多种语言学理论的基础。图论里，聚类系数衡量连接的局部性：图中有许多团或近似团时该系数高。简单 Erdős-Rényi 随机图聚类系数不高；而小世界图这一类随机图具有高聚类系数。",
                "summary": "纯随机不够：缺局部团结构 → 需要小世界式「窗口+随机」。",
                "terms": ["clustering coefficient", "small world graphs"],
            },
            {
                "en": "A particular model introduced by Watts and Strogatz is of high relevance to us as it achieves a good balance between average shortest path and the notion of locality. The generative process of their model is as follows: Construct a regular ring lattice, a graph with n nodes each connected to w neighbors, w/2 on each side. In other words we begin with a sliding window on the nodes. Then a random subset (k%) of all connections is replaced with a random connection. The other (100−k)% local connections are retained.",
                "zh": "Watts–Strogatz 模型与我们高度相关：它在平均最短路径与局部性之间取得良好平衡。生成过程：先构造正则环格——n 个节点各自连接 w 个邻居（左右各 w/2），也即从滑动窗口开始；再把全部连接中随机 k% 替换为随机连接，其余 (100−k)% 局部连接保留。",
                "summary": "小世界配方：先窗口环，再少量随机重连。",
                "terms": ["Watts-Strogatz", "sliding window"],
            },
            {
                "en": "However, deleting such random edges might be inefficient on modern hardware, so we retain it, which will not affect its properties. In summary, to capture these local structures in the context, in BIGBIRD, we define a sliding window attention, so that during self attention of width w, query at location i attends from i−w/2 to i+w/2 keys. In our notation, A(i, i−w/2 : i+w/2)=1 (see Fig. 1b).",
                "zh": "但在现代硬件上删除这些边可能低效，因此我们选择保留局部边（不损害性质）。总结：为捕捉上下文局部结构，BIGBIRD 定义宽度为 w 的滑动窗口注意力——位置 i 的 query 关注从 i−w/2 到 i+w/2 的 key，即 A(i, i−w/2:i+w/2)=1（见图 1b）。",
                "summary": "工程改动：不删局部边，只加随机；窗口形式写进 A。",
                "terms": ["window attention"],
            },
            {
                "en": "As an initial sanity check, we performed basic experiments to test whether these intuitions are sufficient in getting performance close to BERT like models, while keeping attention linear in the number of tokens. We found that random blocks and local window were insufficient in capturing all the context necessary to compete with the performance of BERT.",
                "zh": "作为初步健全性检查，我们做了基础实验：在注意力对 token 数保持线性的前提下，这些直觉是否足以接近 BERT 类模型。结果发现：仅有随机块与局部窗口，不足以捕捉与 BERT 竞争所需的全部上下文。",
                "summary": "消融预警：R+W 还不够，必须上全局（见表 1）。",
                "terms": [],
            },
            {
                "en": "Table 1 (Building block comparison @512): BERT-base MLM/SQuAD/MNLI = 64.2 / 88.5 / 83.4; Random (R) = 60.1 / 83.0 / 80.2; Window (W) = 58.3 / 76.4 / 73.1; R+W = 62.7 / 85.1 / 80.5.",
                "zh": "表 1（512 长度下积木对比）：BERT-base 在 MLM/SQuAD/MNLI 为 64.2 / 88.5 / 83.4；仅 Random 为 60.1 / 83.0 / 80.2；仅 Window 为 58.3 / 76.4 / 73.1；R+W 为 62.7 / 85.1 / 80.5。",
                "summary": "数字对照：W 最弱，R 稍好，R+W 接近但仍低于 BERT → 缺全局。",
                "terms": ["Table 1"],
            },
            {
                "en": "The final piece of BIGBIRD is inspired from our theoretical analysis (Sec. 3), which is critical for empirical performance. More specifically, our theory utilizes the importance of “global tokens” (tokens that attend to all tokens in the sequence and to whom all tokens attend to (see Fig. 1c)). These global tokens can be defined in two ways:",
                "zh": "BIGBIRD 的最后一块积木来自第 3 节的理论分析，且对经验性能至关重要。具体地，理论利用了「全局 token」的重要性：它们关注序列中所有 token，也被所有 token 关注（见图 1c）。全局 token 可用两种方式定义：",
                "summary": "积木③ 全局：对称星形枢纽；理论与实验都依赖它。",
                "terms": ["global tokens"],
            },
            {
                "en": "BIGBIRD-ITC: In internal transformer construction (ITC), we make some existing tokens “global”, which attend over the entire sequence. Concretely, we choose a subset G of indices (with g := |G|), such that A(i, :) = 1 and A(:, i) = 1 for all i ∈ G.",
                "zh": "BIGBIRD-ITC（内部 Transformer 构造）：把已有的某些 token 标成「全局」，使其关注整个序列。具体地，选下标子集 G（g:=|G|），对所有 i∈G 令 A(i,:)=1 且 A(:,i)=1。",
                "summary": "ITC：不新增位置，把现有 token（如问题词）变成枢纽。",
                "terms": ["ITC"],
            },
            {
                "en": "BIGBIRD-ETC: In extended transformer construction (ETC), we include additional “global” tokens such as CLS. Concretely, we add g global tokens that attend to all existing tokens. In our notation, this corresponds to creating a new matrix B ∈ [0,1]^{(N+g)×(N+g)} by adding g rows to matrix A, such that B(i,:)=1 and B(:,i)=1 for all i ∈ {1,…,g}, and B(g+i, g+j)=A(i,j) for all i,j ∈ {1,…,N}. This adds extra location to store context and as we will see in the experiments improves performance.",
                "zh": "BIGBIRD-ETC（扩展 Transformer 构造）：额外加入如 CLS 之类的全局 token。具体地，增加 g 个关注所有已有 token 的全局位，得到 B∈[0,1]^{(N+g)×(N+g)}：对 i=1…g 有 B(i,:)=B(:,i)=1，且 B(g+i,g+j)=A(i,j)。这为上下文提供额外存储位置，实验表明能提升性能。",
                "summary": "ETC：真的插入新全局位当外部记忆；矩阵从 N 扩到 N+g。",
                "terms": ["ETC", "CLS"],
            },
            {
                "en": "The final attention mechanism for BIGBIRD (Fig. 1d) has all three of these properties: queries attend to r random keys, each query attends to w/2 tokens to the left of its location and w/2 to the right of its location and they contain g global tokens (The global tokens can be from existing tokens or extra added tokens). We provide implementation details in App. D.",
                "zh": "最终的 BIGBIRD 注意力（图 1d）同时具备这三条：query 关注 r 个随机 key；每个 query 关注其位置左侧 w/2 与右侧 w/2 个 token；并包含 g 个全局 token（可来自已有 token 或额外添加）。实现细节见附录 D。",
                "summary": "总装配公式：每行 ≈ 随机 r + 窗口 w + 经全局星形连通。",
                "terms": ["BIGBIRD"],
            },
        ],
    },
    {
        "id": "theory",
        "title": "3 Theoretical Results 理论结果",
        "paras": [
            {
                "en": "In this section, we will show that sparse attention mechanisms are as powerful and expressive as full-attention mechanisms in two respects. First, we show that when sparse attention mechanisms are used in a standalone encoder (such as BERT), they are Universal Approximators of sequence to sequence functions in the style of Yun et al. Second, unlike contemporaneous work, we further show that sparse encoder-decoder transformers are Turing Complete (assuming the same conditions defined in Pérez et al.).",
                "zh": "本节从两方面说明稀疏注意力与全注意力同样强大、同样有表达力。第一，用于独立编码器（如 BERT）时，稀疏注意力按 Yun 等的意义是序列到序列函数的万能近似器。第二，与同期工作不同，我们进一步证明稀疏 encoder-decoder Transformer 在 Pérez 等相同假设下是图灵完备的。",
                "summary": "理论双结果：编码器万能近似；编解码器图灵完备。",
                "terms": ["universal approximator", "Turing complete"],
            },
            {
                "en": "Complementing the above positive results, we also show that moving to a sparse-attention mechanism incurs a cost, i.e. there is no free lunch. In Sec. 3.4, we show lower bounds by exhibiting a natural task where any sufficiently sparse mechanism will require polynomially more layers.",
                "zh": "作为正面结果的补充，我们也说明转向稀疏注意力会有代价——没有免费午餐。第 3.4 节给出下界：展示一个自然任务，其上任何足够稀疏的机制都需要多项式更多的层数。",
                "summary": "没有免费午餐：太稀疏可能要用更深网络补回来。",
                "terms": ["lower bounds"],
            },
            {
                "en": "Notation (Sec. 3.1). The complete Transformer encoder stack is the repeated application of a single-layer encoder. We denote the class of such Transformer encoder stacks, defined using the generalized encoder (Sec. 2), by T_{H,m,q}^D which consists of H-heads with head size m and q is the hidden layer size of the output network, and the attention layer is defined by the directed graph D.",
                "zh": "记号（§3.1）。完整 Transformer 编码器栈就是单层编码器的反复叠加。用第 2 节广义编码器定义的这类编码器栈记为 T_{H,m,q}^D：含 H 个头、头维 m、输出网络隐层宽 q，注意力由图 D 定义。",
                "summary": "统一记号：表达力讨论都在类 T^D 里进行。",
                "terms": [],
            },
            {
                "en": "The key difference between our proposed attention mechanism to that of Vaswani et al. / Yun et al. is that we add a special token at the beginning of each sequence and assign it a special vector. We will refer to this as x₀. Therefore our graph D will have vertex set {0} ∪ [n] = {0, 1, 2, …, n}. We will assume that this extra node and its respective vector will be dropped at the final output layer of transformer.",
                "zh": "与 Vaswani / Yun 等的关键差异是：我们在每个序列开头加入特殊 token，并赋予特殊向量，记为 x₀。因此图 D 的顶点集为 {0}∪[n]。假定该额外节点及其向量在 Transformer 最终输出层被丢弃。",
                "summary": "理论构造里显式加「第 0 号全局位」——后面星形图就靠它。",
                "terms": ["global tokens"],
            },
            {
                "en": "Finally, we need to define the function class and distance measure for proving universal approximation property. Let F_CD denote the set of continuous functions f : [0,1]^{n×d} → R^{n×d} which are continuous with respect to the topology defined by ℓ_p norm.",
                "zh": "为证明万能近似，还需定义函数类与距离。令 F_CD 表示对 ℓ_p 拓扑连续的函数 f:[0,1]^{n×d}→R^{n×d} 的集合。",
                "summary": "逼近对象：紧方体上的连续 seq2seq 函数。",
                "terms": [],
            },
            {
                "en": "Definition 1 (star-graph). The star-graph S centered at 0 is the graph defined on {0,…,n}. The neighborhood of all vertices i is N(i)={0,i} for i∈{1…n} and N(0)={1,…,n}.",
                "zh": "定义 1（星形图）：以 0 为中心的星形图 S 定义在顶点集 {0,…,n} 上。对 i=1…n，N(i)={0,i}；而 N(0)={1,…,n}。",
                "summary": "星形 = 一个中心连所有人；对应「全局 token」的图论骨架。",
                "terms": ["star-graph"],
            },
            {
                "en": "Theorem 1. Given 1 < p < ∞ and ε > 0, for any f ∈ F_CD, there exists a transformer with sparse-attention g ∈ T_{H,m,q}^D such that d_p(f,g) ≤ ε where D is any graph containing star graph S.",
                "zh": "定理 1：给定 1<p<∞ 与 ε>0，对任意 f∈F_CD，存在带稀疏注意力的 Transformer g∈T_{H,m,q}^D，使得 d_p(f,g)≤ε，其中图 D 是任意包含星形图 S 的图。",
                "summary": "主定理一句话：只要稀疏图里「含有星形全局结构」，就能逼近连续 seq2seq 函数。",
                "terms": ["Theorem 1"],
            },
            {
                "en": "Proof sketch Step 1: Approximate F_CD by piece-wise constant functions. Since f is continuous on a bounded domain, approximate it by a suitable piece-wise constant function on a δ-grid G_δ, so that one may work with a discrete map f̄ : G_δ → R^{n×d} with d_p(f, f̄) ≤ ε/3.",
                "zh": "证明提纲第 1 步：用分段常值函数逼近 F_CD。因 f 在有界域上连续，在粒度 δ 的网格 G_δ 上用合适的分段常值函数逼近，从而可处理离散映射 f̄，并使 d_p(f,f̄)≤ε/3。",
                "summary": "先把连续目标离散成网格上的分段常值问题。",
                "terms": [],
            },
            {
                "en": "Proof sketch Step 2: Approximate piece-wise constant functions by modified transformers. This is the key step: the self-attention mechanism is used to generate a contextual mapping of the input—a unique code for the pair consisting of a matrix (X, x_i) and a column—so that feed-forward layers can map each code to a unique output column.",
                "zh": "证明提纲第 2 步：用改造后的 Transformer 逼近分段常值函数。这是关键步：用自注意力生成输入的上下文映射——为矩阵 (X, x_i) 与某一列构造唯一编码——以便前馈层把每个编码映到唯一输出列。",
                "summary": "上下文映射 = 给「整句+当前位置」打唯一条码，供 FFN 查表。",
                "terms": ["contextual mapping"],
            },
            {
                "en": "Creating a contextual mapping with a sparse attention mechanism is quite a challenge. In particular, because each query only attends to a few keys, it is not at all clear that sufficient information can be corralled to make a contextual embedding of the entire matrix. To get around this, we develop a sparse shift operator… The second key ingredient is the use of additional global token. By carefully applying the operator to a set of chosen ranges, we will show that each column will contain a unique mapping of the full mapping. Therefore, we can augment the loss of inner-products in the self attention mechanism by using multiple layers and an auxiliary global token.",
                "zh": "用稀疏注意力构造上下文映射相当困难：每个 query 只看少数 key，能否汇聚整矩阵信息并不显然。为此作者发展稀疏移位算子……第二关键成分是额外全局 token。通过对选定区间仔细施加算子，可证明每一列都含有完整映射的唯一编码。因此，可用多层与辅助全局 token 弥补自注意力中内积数量的损失。",
                "summary": "为什么理论死掐全局：没有中心枢纽，稀疏下上下文编码很难做出来。",
                "terms": ["contextual mapping", "global tokens"],
            },
            {
                "en": "Proof sketch Step 3: Approximate modified transformers by original Transformers. The final step is to approximate the modified transformers by the original transformer which uses ReLU and softmax. Full details are in App. A.",
                "zh": "证明提纲第 3 步：用原始 Transformer 逼近改造版。最后把使用特殊算子的改造版，用带 ReLU 与 softmax 的原始 Transformer 逼近。细节见附录 A。",
                "summary": "理论玩具算子 → 现实 ReLU/softmax 栈，误差可控。",
                "terms": [],
            },
            {
                "en": "Turing Completeness (Sec. 3.3). Pérez et al. showed that the full transformer based on a quadratic attention mechanism is Turing Complete, assuming arbitrary precision. It is natural to ask if the full attention mechanism is necessary. We show that this is indeed not the case: we can use a sparse encoder and sparse decoder to simulate any Turing Machine.",
                "zh": "图灵完备（§3.3）。Pérez 等证明基于二次注意力的完整 Transformer 在任意精度假设下图灵完备。自然要问：全注意力是否必要？作者证明并非必要：可用稀疏编码器与稀疏解码器模拟任意图灵机。",
                "summary": "稀疏编解码仍可图灵完备（精度假设与 Pérez 相同）。",
                "terms": ["Turing complete"],
            },
            {
                "en": "Most of the construction of Pérez et al. goes through for sparse attentions, except for their addressing scheme to point back in history (Lemma B.4 in Pérez et al.). We show how to simulate this using a sparse attention mechanism and defer the details to App. B.",
                "zh": "Pérez 等的构造对稀疏注意力大多仍然成立，例外是其回指历史的寻址方案（其 Lemma B.4）。作者说明如何用稀疏注意力模拟该寻址，细节推迟到附录 B。",
                "summary": "难点不在「能不能算」，而在「如何稀疏地找回带上历史格子」。",
                "terms": [],
            },
            {
                "en": "Limitations / Task 1 (Sec. 3.4). Consider finding, for each unit vector in a length-n sequence, the furthest vector in the sequence. Formally: given n unit vectors {u₁,…,uₙ}, find f(u₁,…,uₙ)→(u_{1*},…,u_{n*}) where for fixed j, j* = arg max_k ‖u_k − u_j‖₂². For full attention this is easy via all pairwise inner products.",
                "zh": "局限 / 任务 1（§3.4）。考虑：对长度为 n 的单位向量序列中的每一个，找出序列中与它最远的向量。形式化：给定 {u₁,…,uₙ}，求 f→(u_{1*},…,u_{n*})，其中对固定 j 有 j*=arg max_k ‖u_k−u_j‖₂²。全注意力可通过全部成对内积轻松完成。",
                "summary": "反例任务：最远向量搜索——本质上要看几乎所有成对内积。",
                "terms": ["Task 1"],
            },
            {
                "en": "Proposition 1. There exists a single layer full self-attention that can evaluate Task 1, but for any sparse-attention graph D with Õ(n) edges (i.e. inner product evaluations), would require Õ̃(n^{1−o(1)}) layers (under Orthogonal Vector Conjecture).",
                "zh": "命题 1：存在单层全自注意力可计算任务 1；但对任意仅有 Õ(n) 条边（即内积次数）的稀疏注意力图 D，在正交向量猜想（OVC）下需要 Õ̃(n^{1−o(1)}) 层。",
                "summary": "稀疏的代价：边太少时，要用近多项式层数才能补回「全对比较」。",
                "terms": ["OVC", "Proposition 1"],
            },
        ],
    },
    {
        "id": "expts",
        "title": "4 Experiments: NLP 自然语言实验",
        "paras": [
            {
                "en": "In this section our goal is to showcase benefits of modeling longer input sequence for NLP tasks, for which we select three representative tasks. We begin with basic masked language modeling (MLM) to check if better contextual representations can be learnt by utilizing longer contiguous sequences. Next, we consider QA with supporting evidence, for which capability to handle longer sequence would allow us to retrieve more evidence using crude systems like TF-IDF/BM25.",
                "zh": "本节目标是展示为 NLP 任务建模更长输入序列的好处，选取三类代表性任务。先从基础掩码语言模型（MLM）入手，检验利用更长连续序列能否学到更好的上下文表示；再考虑带支持证据的问答——更长序列使我们可以用 TF-IDF/BM25 等粗检索系统取回更多证据。",
                "summary": "实验逻辑：先 MLM 验表示，再 QA/摘要吃长上下文。",
                "terms": ["MLM"],
            },
            {
                "en": "Pretraining and MLM. We follow Devlin et al. / Liu et al. to create base and large versions of BIGBIRD and pretrain it using MLM objective. We warm-start from the public RoBERTa checkpoint. Both BIGBIRD and Longformer perform better than limited length RoBERTa, with BIGBIRD-ETC performing the best. We trained on a reasonable 16GB memory/chip with batch size of 32–64. Our memory efficiency is due to efficient blocking and sparsity structure of the sparse attention mechanism described in Sec. 2.",
                "zh": "预训练与 MLM：按 BERT/RoBERTa 做法构建 base/large 版 BIGBIRD，用 MLM 目标预训练，并从公开 RoBERTa 检查点热启动。BIGBIRD 与 Longformer 均优于长度受限的 RoBERTa，其中 BIGBIRD-ETC 最好。可在约 16GB/芯片、batch 32–64 上训练；内存效率来自第 2 节所述稀疏注意力的高效分块与稀疏结构。",
                "summary": "工程对照：16GB 能训长序列 → 块稀疏不是纸上谈兵。",
                "terms": ["ETC", "block sparse"],
            },
            {
                "en": "Question Answering. We consider Natural Questions, HotpotQA-distractor, TriviaQA-wiki, and WikiHop. These tasks need short/long answers, supporting facts, or multi-document multiple choice. As these tasks are very competitive, highly engineered systems exist for each dataset; for fair comparison we used additional regularization for training BIGBIRD (details in App. E.2).",
                "zh": "问答：考虑 Natural Questions、HotpotQA-distractor、TriviaQA-wiki 与 WikiHop。这些任务需要短/长答案、支持事实或多文档多选。由于竞争激烈，各数据集都有高度工程化系统；为公平比较，训练 BIGBIRD 时使用了额外正则（见附录 E.2）。",
                "summary": "QA 四件套：考验跨段证据与多跳，正是长上下文的主场。",
                "terms": [],
            },
            {
                "en": "On development (base size), BIGBIRD-ETC with expanded global tokens consistently outperforms other models (Table 2). On hidden test (large ETC), BIGBIRD-ETC is the new state-of-the-art on Natural Questions Long Answer, TriviaQA, and WikiHop; on HotpotQA it ranks near the top by F1/EM. Both Longformer and BIGBIRD outperform shorter-context models, underscoring the importance of longer context.",
                "zh": "开发集（base）上，带扩展全局 token 的 BIGBIRD-ETC 持续优于其他模型（表 2）。隐藏测试（large ETC）上，BIGBIRD-ETC 在 Natural Questions 长答案、TriviaQA、WikiHop 上达到新 SOTA；HotpotQA 的 F1/EM 也位居前列。Longformer 与 BIGBIRD 都超过短上下文模型，说明更长上下文很重要。",
                "summary": "读表要点：ETC 全局扩展在 QA 上最稳；长上下文是共同赢家。",
                "terms": ["ETC", "ITC"],
            },
            {
                "en": "Classification. We experiment on datasets of different lengths and contents, specifically various document classification and GLUE tasks. Following BERT, we used one layer with cross entropy loss on top of the first [CLS] token. We see that gains of using BIGBIRD are more significant when we have longer documents and fewer training examples. For instance, using base sized model, BIGBIRD improves state-of-the-art for Arxiv dataset by about 5% points.",
                "zh": "分类：在不同长度与内容的数据集上实验，包括多种文档分类与 GLUE。按 BERT，在首个 [CLS] 上接一层交叉熵。观察到：文档更长、训练样本更少时，BIGBIRD 的收益更显著。例如 base 模型上，Arxiv 数据集相对 SOTA 约提升 5 个百分点。",
                "summary": "分类规律：越长越少样本，长上下文红利越大。",
                "terms": ["CLS"],
            },
            {
                "en": "Encoder-Decoder / Summarization. For encoder-decoder setups, both sides can suffer quadratic cost from full self-attention. We introduce BIGBIRD sparse attention only on the encoder side, because in practical generative applications the output is typically much shorter than the input (e.g. summarization: median output ∼200 while input median >3000). Thus it is more efficient to use sparse attention for the encoder and full self-attention for the decoder.",
                "zh": "Encoder-Decoder / 摘要：编解码两边都可能因全自注意力遭受二次代价。我们只在编码器侧引入 BIGBIRD 稀疏注意力——因为实际生成中输出通常远短于输入（如摘要：输出中位长约 200，输入中位长 >3000）。因此对编码器用稀疏、对解码器保留全注意力更划算。",
                "summary": "落地折中：长输入稀疏编码 + 短输出全注意力解码。",
                "terms": [],
            },
            {
                "en": "On long-document abstractive summarization (Arxiv, PubMed, BigPatent), modeling longer context brings significant improvement (Table 4). Salient content can be evenly distributed (by design in BigPatent), and longer documents exhibit richer discourse structure with more abstractive summaries—observing more context helps.",
                "zh": "在长文档抽象摘要（Arxiv、PubMed、BigPatent）上，建模更长上下文带来显著提升（表 4）。显著内容可能均匀分布（BigPatent 即如此设计），且长文档话语结构更丰富、摘要更抽象——看到更多上下文有帮助。",
                "summary": "摘要为什么吃长度：重点不在开头 512，而在全文分布。",
                "terms": [],
            },
        ],
    },
    {
        "id": "genomics",
        "title": "5 Experiments: Genomics 基因组实验",
        "paras": [
            {
                "en": "There has been a recent upsurge in using deep learning for genomics data, which has resulted in improved performance on several biologically-significant tasks such as promoter site prediction, methylation analysis, predicting functional effects of non-coding variant, etc. These approaches consume DNA sequence fragments as inputs, and therefore we believe longer input sequence handling capability of BIGBIRD would be beneficial as many functional effects in DNA are highly non-local.",
                "zh": "近期深度学习用于基因组数据升温，在启动子位点预测、甲基化分析、非编码变异功能效应预测等生物学重要任务上提升明显。这些方法以 DNA 片段为输入；由于 DNA 许多功能效应高度非局部，我们认为 BIGBIRD 处理更长输入的能力会有帮助。",
                "summary": "动机：生物序列的「远程调控」天然需要长上下文。",
                "terms": [],
            },
            {
                "en": "Taking inspiration from NLP, we learn powerful contextual representations for DNA fragments utilizing abundant unlabeled data (e.g. human reference genome) via MLM pretraining. Instead of operating on base pairs, we first segment DNA into tokens via byte-pair encoding (vocab 32K; ~8.78 bp/token on average), increasing effective context. On held-out MLM, BIGBIRD (seqlen 4096) reaches BPC 1.12 vs BERT-512 at 1.23 and SRILM at 1.57 (Table 5).",
                "zh": "受 NLP 启发，我们利用丰富的无标数据（如人类参考基因组）通过 MLM 预训练学习 DNA 片段的强上下文表示。不直接以碱基对为单位，而先用 BPE 分词（词表 32K，平均约 8.78 bp/token）以进一步拉长有效上下文。在留出集 MLM 上，BIGBIRD（长度 4096）BPC 为 1.12，优于 BERT-512 的 1.23 与 SRILM 的 1.57（表 5）。",
                "summary": "DNA 也做 MLM：分词 + 长序列 → BPC 明显更好。",
                "terms": ["MLM", "BPC"],
            },
            {
                "en": "Promoter Region Prediction. The task is to classify a DNA fragment as promoter or non-promoter. Finetuning pretrained BIGBIRD achieves F1 99.9 vs prior best DeePromoter 95.6 (Table 6)—nearly perfect accuracy with about a 5% jump.",
                "zh": "启动子区域预测：判断 DNA 片段是否为启动子。微调预训练 BIGBIRD 得到 F1 99.9，对比此前最佳 DeePromoter 95.6（表 6）——接近完美，约提升 5 个百分点。",
                "summary": "下游①：启动子分类几乎打满。",
                "terms": [],
            },
            {
                "en": "Chromatin-Profile Prediction. Predict 919 chromatin profiles (TF / DHS / HM) from non-coding DNA. BIGBIRD improves especially on histone-mark (HM) AUC 88.7 vs DeepSea 85.6 (Table 7); HM is known to have longer-range correlations than the others.",
                "zh": "染色质谱预测：从非编码 DNA 预测 919 项染色质谱（TF / DHS / HM）。BIGBIRD 尤其在组蛋白标记（HM）上提升：AUC 88.7 vs DeepSea 85.6（表 7）；已知 HM 比其他项具有更长程相关。",
                "summary": "下游②：长程相关的 HM 任务最吃长上下文红利。",
                "terms": [],
            },
        ],
    },
    {
        "id": "conclusion",
        "title": "6 Conclusion 结论",
        "paras": [
            {
                "en": "We propose BIGBIRD: a sparse attention mechanism that is linear in the number of tokens. BIGBIRD satisfies a number of theoretical results: it is a universal approximator of sequence to sequence functions and is also Turing complete. Theoretically, we use the power of extra global tokens to preserve the expressive powers of the model. We complement these results by showing that moving to sparse attention mechanism do incur a cost. Empirically, BIGBIRD gives state-of-the-art performance on a number of NLP tasks such as question answering and long document classification. We further introduce attention based contextual language model for DNA and fine-tune it for down stream tasks such as promoter region prediction and predicting effects of non-coding variants.",
                "zh": "我们提出 BIGBIRD：对 token 数线性的稀疏注意力。它满足多项理论结果：是序列到序列函数的万能近似器，并且图灵完备。理论上，我们借助额外全局 token 保持模型表达力；同时补充说明转向稀疏仍有代价。经验上，BIGBIRD 在问答与长文档分类等多种 NLP 任务上达到 SOTA。我们还引入基于注意力的 DNA 上下文语言模型，并微调到启动子预测与非编码变异效应等下游任务。",
                "summary": "收束：线性稀疏 + 全局保表达力 + NLP/基因组实证；稀疏有代价但值得。",
                "terms": ["BIGBIRD", "global tokens"],
            },
        ],
    },
    {
        "id": "blockimpl",
        "title": "实现要点：块稀疏（与附录/工程叙述对齐）",
        "paras": [
            {
                "en": "In practice, BigBird implements the sparse pattern at block granularity rather than selecting arbitrary individual token neighbors for every query. The sequence is partitioned into blocks; random, window, and global connections are realized as block-level masks so that each allowed block-pair can be computed with dense matrix multiplication kernels.",
                "zh": "实践中，BigBird 在块粒度上实现稀疏图案，而不是让每个 query 任意挑选零散 token 邻居。序列被分成块；随机、窗口与全局连接都落实为块级掩码，从而使每个被允许的块对可用密集矩阵乘内核计算。",
                "summary": "工程精髓：稀疏在块与块之间；块内仍 dense GEMM。",
                "terms": ["block sparse", "block mask"],
                "figure": "block",
            },
            {
                "en": "This block-sparse realization is crucial for accelerators: scattered token-level gathers destroy memory coalescing and under-utilize Tensor Cores, whereas block masks preserve contiguous computation inside each selected block while still keeping the number of blocks linear in sequence length. With global g, window w and random r treated as constants (or slowly growing), attention cost scales as O(n · (g + w + r)) rather than O(n²).",
                "zh": "这种块稀疏实现对加速器至关重要：token 级零散 gather 破坏合并访存、吃不满 Tensor Core；而块掩码在每个选中块内部保持连续计算，同时使块的数量仍对序列长度保持线性。当全局 g、窗口 w、随机 r 视为常数（或缓慢增长）时，注意力代价为 O(n·(g+w+r)) 而非 O(n²)。",
                "summary": "复杂度记账：线性来自「每行度数≈常数」；块化只是让 GPU 真能跑到这个渐近。",
                "terms": ["Tensor Core", "O(n) inner products"],
            },
            {
                "en": "Comparison note (vs Longformer): Longformer uses sliding window + task-motivated global tokens. BigBird adds random (block) edges for small-world connectivity, proves universal approximation / Turing completeness under star-containing graphs, and emphasizes ETC-style extra global tokens plus block-sparse kernels for hardware.",
                "zh": "对照笔记（相对 Longformer）：Longformer 使用滑动窗口 + 任务驱动的全局 token。BigBird 额外加入随机（块）边以获得小世界连通性，在「含星形」图上证明万能近似/图灵完备，并强调 ETC 式额外全局 token 与面向硬件的块稀疏核。",
                "summary": "和 Longformer 一句话差：多随机边 + 更完整理论 + 块稀疏工程叙事。",
                "terms": ["Longformer", "ETC"],
            },
        ],
    },
]

GLOSSARY = [
    ("BIGBIRD", "本文提出的稀疏注意力：全局 + 滑动窗口 + 随机边，复杂度对长度线性。"),
    ("full attention", "每个 query 关注所有 key 的标准自注意力，复杂度 O(n²)。"),
    ("full self-attention", "同 full attention：序列内全体两两注意力。"),
    ("sparse attention", "每个 query 只关注 key 的一个子集。"),
    ("quadratic dependency", "计算/内存随序列长度平方增长。"),
    ("global tokens", "与全序列双向（或按定义）连接的枢纽 token，数量 O(1)。"),
    ("window attention", "每个位置只关注左右各 w/2 邻域。"),
    ("random attention", "每个位置额外关注 r 个随机位置（常按块）。"),
    ("adjacency matrix", "A(i,j)=1 表示 i 对 j 做注意力。"),
    ("graph sparsification", "减少图中边数同时尽量保留完全图的重要性质。"),
    ("Erdős-Rényi", "每条边独立以固定概率出现的随机图模型。"),
    ("small world graphs", "高局部聚类 + 短平均路径的图；Watts–Strogatz 是代表。"),
    ("clustering coefficient", "衡量局部抱团程度的图统计量。"),
    ("Watts-Strogatz", "先做环上窗口邻接，再随机重连一部分边的小世界模型。"),
    ("sliding window", "沿序列滑动的固定宽度邻域连接。"),
    ("ITC", "Internal Transformer Construction：把已有 token 标成全局。"),
    ("ETC", "Extended Transformer Construction：额外插入全局 token。"),
    ("star-graph", "一个中心连接所有其他节点的图，理论证明的关键结构。"),
    ("universal approximator", "能以任意精度逼近某类函数（此处为连续 seq2seq）。"),
    ("Turing complete", "在假设下可模拟任意图灵机计算。"),
    ("block sparse", "以块为单位的稀疏掩码；块内仍做密集运算。"),
    ("block mask", "决定哪些 block-pair 参与计算的块级掩码。"),
    ("block sparsity", "利用块结构降低复杂度/提高核效率的稀疏方式。"),
    ("Longformer", "窗口+全局的近亲工作；BigBird 额外加随机并强化理论。"),
    ("Sparse Transformer", "Child et al. 的固定稀疏图案注意力。"),
    ("out-neighbors N(i)", "图中节点 i 的出邻居集合，即 query i 允许看见的 key 集合。"),
    ("generalized attention", "由有向图 D 规定允许内积集合的注意力形式。"),
    ("complete digraph", "任意有序点对都有弧的有向完全图＝全注意力。"),
    ("expander", "稀疏却具有类似完全图扩展/谱性质的图。"),
    ("average path length", "图中节点对最短路径长度的平均，越小信息传得越快。"),
    ("locality", "连接或依赖主要集中在邻近位置的现象。"),
    ("locality of reference", "访问/依赖集中在邻近地址或邻近 token。"),
    ("mixing time", "随机游走收敛到平稳分布所需时间；短则信息混合快。"),
    ("contextual mapping", "把整句上下文编码进每个位置表示的唯一映射，用于万能近似证明。"),
    ("O(n) inner products", "注意力内积次数随序列长度线性增长。"),
    ("sequence length 512", "常见全注意力硬件上限的量级示例。"),
    ("permutation equivariant", "打乱 token 顺序时输出按同一置换变换；本身不编码绝对顺序。"),
    ("expressivity", "模型可表示/逼近的函数类有多丰富。"),
    ("self-attention", "序列内部用 Q/K/V 计算的注意力。"),
    ("SIMD", "单指令多数据并行硬件范式（GPU/TPU）。"),
    ("pretraining", "在通用数据上先训练再迁移到下游。"),
    ("Transformer", "以自注意力为核心的序列模型族。"),
    ("BERT", "双向编码器预训练代表模型。"),
    ("T5", "Text-to-Text Transfer Transformer。"),
    ("seq2seq", "序列到序列（编码-解码）设定。"),
    ("LSTM", "长短期记忆循环网络。"),
    ("CLS", "分类/汇聚用特殊 token，常可兼作全局位。"),
    ("softmax", "把分数归一化为注意力权重的函数。"),
    ("Table 1", "512 长度下 Random/Window 积木消融表。"),
    ("Theorem 1", "含星形图的稀疏注意力是连续 seq2seq 的万能近似器。"),
    ("Task 1", "最远向量检索任务，用于证明稀疏下界。"),
    ("Proposition 1", "全注意力一层可解 Task 1；Õ(n) 边稀疏需近多项式层。"),
    ("OVC", "Orthogonal Vector Conjecture，精细复杂度常用假设。"),
    ("lower bounds", "说明稀疏必然付出层数/深度代价的理论下界。"),
    ("MLM", "掩码语言模型预训练目标。"),
    ("BPC", "Bits Per Character，字符级压缩/困惑度相关指标。"),
    ("Tensor Core", "GPU 上适合规则块矩阵乘的张量计算单元。"),
]

REFS = [
    {
        "level": "本篇",
        "title": "Big Bird: Transformers for Longer Sequences",
        "why": "逐段精读对象；公式与 Fig.1 / Table 1–7 以 PDF 为准。",
        "url": "./paper.pdf",
        "ext": "https://arxiv.org/abs/2007.14062",
    },
    {
        "level": "对照",
        "title": "Longformer",
        "why": "窗口+全局任务向经典；与 BigBird 三件套对照读。",
        "url": "../longformer/index.html",
        "ext": "https://arxiv.org/abs/2004.05150",
    },
    {
        "level": "近亲",
        "title": "ETC: Encoding Long and Structured Data in Transformers",
        "why": "全局 token / ETC 构造的直接前驱。",
        "url": "https://arxiv.org/abs/2004.08483",
        "ext": "",
    },
    {
        "level": "理论前驱",
        "title": "Yun et al. — Transformers as universal approximators",
        "why": "全注意力万能近似；Theorem 1 的对照起点。",
        "url": "https://arxiv.org/abs/1912.10077",
        "ext": "",
    },
    {
        "level": "理论前驱",
        "title": "Pérez et al. — Turing Completeness of Transformers",
        "why": "全 Transformer 图灵完备；稀疏版证明的假设来源。",
        "url": "https://arxiv.org/abs/1901.03429",
        "ext": "",
    },
    {
        "level": "前驱",
        "title": "Watts–Strogatz 小世界网络",
        "why": "随机捷径 / 高聚类短路径的图论源头；对照 BigBird 随机边。",
        "url": "../watts-strogatz/index.html",
        "ext": "https://doi.org/10.1038/30918",
    },
    {
        "level": "专题",
        "title": "稀疏注意力专题页",
        "why": "把 BigBird 放回稀疏注意力谱系里对照。",
        "url": "../sparse-attention/index.html",
        "ext": "",
    },
]
